proxy:
  image: hiropppe/rasc_test
  dns: 172.17.42.1
  hostname: proxy.containers.dev
  ports:
    - "8080:8080"
  user: root
  
server:
  image: hiropppe/rasc_test
  dns: 172.17.42.1
  hostname: server.containers.dev
  ports:
    - "8081:8080"
  user: root

worker1:
  image: hiropppe/rasc_test
  dns: 172.17.42.1
  hostname: worker1.containers.dev
  ports:
    - "8082:8080"
  user: root

worker2:
  image: hiropppe/rasc_test
  dns: 172.17.42.1
  hostname: worker2.containers.dev
  ports:
    - "8083:8080"
  user: root
